# Generated by Django 2.1.1 on 2018-09-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('languageName', models.CharField(default='SOME STRING', max_length=100)),
                ('welcomeString', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Dodaj kurs',
                'verbose_name_plural': 'Dodaj kurs',
            },
        ),
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('lessonId', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('topic', models.TextField(default='a')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.courses')),
            ],
            options={
                'verbose_name_plural': 'Dodaj lekcje',
            },
        ),
        migrations.CreateModel(
            name='wordsDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=50)),
                ('websiteUsersMeaning', models.TextField(max_length=50)),
                ('languageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lessons')),
            ],
            options={
                'verbose_name_plural': 'Dodaj słówka',
            },
        ),
    ]
