# Generated by Django 2.1.1 on 2018-09-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('languageName', models.CharField(default='SOME STRING', max_length=100)),
                ('welcomeString', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Kurs',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lessonId', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('topic', models.TextField(default='a')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Courses')),
            ],
            options={
                'verbose_name_plural': 'Lekcja',
            },
        ),
        migrations.CreateModel(
            name='WordsDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='Error', max_length=50)),
                ('websiteUserMeaning', models.CharField(default='Error', max_length=50)),
                ('partOfSpech', models.CharField(default='Error', max_length=20)),
                ('levelOfEducation', models.CharField(choices=[('Ad', 'Zaawansowany'), ('Bg', 'Początkujący'), ('It', 'Średnio zaawansowany')], default='Bg', max_length=2)),
                ('languageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lessons')),
            ],
            options={
                'verbose_name_plural': 'Słówka',
            },
        ),
    ]
